<?php

namespace App\Http\Controllers\Api\Refineries;

use App\Helpers\ApiResponse;
use App\Helpers\CustomGenerator;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\Refineries\ProgramRequest;
use App\Http\Resources\ProgramResource;
use App\Models\Api\Program;
use Illuminate\Http\Request;

class ProgramController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $marketer_id = 1;
        // Fetch all product types from the database
        $programs = Program::where('marketer_id', $marketer_id)
            ->latest()
            ->paginate();
        // Add metadata to the response
        $metadata = $programs;
        // Transform the items
        $data = ProgramResource::collection($programs);
        // Return response
        return ApiResponse::success($data, 'successful', 200, $metadata); 
    }


    /**
     * Display the specified resource.
     */
    public function show(Program $program)
    {
        $program = new ProgramResource($program);
        return ApiResponse::success($program, 'successful');
    }

    /**
     * Refinery: Update the specified resource in storage.
     */
    public function update(ProgramRequest $request, Program $program)
    {
        // Validate the request data
        $data = $request->validated();

        // Approve the program request
        if($data['status'] == 'approved'){
            // Generate ATC
            $data['atc_number'] = CustomGenerator::generateUniqueATC();
            // Generated by
            $data['generated_by'] = request()?->user()?->id ?? 1;
        }

        // Update the program
        $program->update($data);

        return ApiResponse::success($program, 'Program updated', 200);
    }


}
